#!/bin/bash

max_length=48
cookies=(
    "42 is the answer"
    "Add Harpoon: <span size='x-large'><b>󱁐</b></span> a"
    "Back to Project View: <span size='x-large'><b>󱁐</b></span> pv"
    "Backward by Word: b ge B gB"
    "Change Inside Brackets: ci("
    "Change Inside Quotes: ci\""
    "Change Inside Tag: cit"
    "Change Permissions: <span size='x-large'><b>󱁐</b></span> x"
    "Change in Word: ciw"
    "Change to Inner Block: cib"
    "Change to Inner Paragraph: cip"
    "Change to Line: cil"
    "Code is love"
    "Command not found"
    "Copy Line: yy"
    "Copy to Another: <span size='x-large'><b>󱁐</b></span> y|Y"
    "Cut Line: dd"
    "Delete Inside Word: diw"
    "Delete Line: D"
    "Delete to End of Word: daw"
    "Don't trust the Wi-Fi"
    "Embrace the CLI"
    "Exit 0 means success"
    "Find next: t f / *"
    "Find previous: T F ? #"
    "Fix one bug, create five more"
    "Format (Alternate): <span size='x-large'><b>󱁐</b></span> = ap"
    "Format: <span size='x-large'><b>󱁐</b></span> f"
    "Forward by Word: e w E W"
    "Go to Definition: gd"
    "Go to Imported File: gf"
    "Go to beginning line: 0"
    "Go to end file: G"
    "Go to end line: $"
    "Go to first character: ^"
    "Go to next bracket/block: }"
    "Go to previous bracket/block: {"
    "Go to start file: gg"
    "Go to top: g_"
    "Harpoons: <span size='x-large'><b>󱁐</b></span> h1~8"
    "I code, therefore I am"
    "In code we trust"
    "Join Lines: J"
    "Just one more feature..."
    "LDUR: j h k l"
    "Life is binary"
    "Match: %"
    "Move Line Down: <span size='x-large'><b>󱁐</b></span> j"
    "Move Line Up: <span size='x-large'><b>󱁐</b></span> k"
    "No coffee, no forcee"
    "Paste After: p"
    "Paste Before: P"
    "Ping your thoughts"
    "Redo: Ctrl + r"
    "Remove Harpoon: <span size='x-large'><b>󱁐</b></span> A"
    "Rename Function: <span size='x-large'><b>󱁐</b></span> vrn"
    "Replace Harpoons: <span size='x-large'><b>󱁐</b></span> Ctrl 1~8"
    "Scroll down: Ctrl + d"
    "Scroll up: Ctrl + u"
    "Search Inside Files: <span size='x-large'><b>󱁐</b></span> ps"
    "Search by File Name: <span size='x-large'><b>󱁐</b></span> pf"
    "See Harpoons: Ctrl + e"
    "Shell yeah!"
    "Shift happens"
    "Stay hydrated"
    "Substitute Words: <span size='x-large'><b>󱁐</b></span> s"
    "Terminal to Vim: (pre)!!sh (post):r!"
    "Test, debug, repeat"
    "The cake is a lie"
    "There’s no place like ~"
    "Think outside the prompt"
    "Trust no script"
    "Undo: u"
    "Use :w more often"
    "You forgot sudo"
    "echo Hello, world!"
    "rm -rf 'bad vibes'"
    "rm -rf today"
    "sudo chill"
)

quote="${cookies[RANDOM % ${#cookies[@]}]}"
echo -n "<span size='x-large'><b>⎡</b></span>$quote<span size='x-large'><b>⎦</b></span>"
